textext/textext

- textext.py
Resolves issue #19
Document size determination during TexText node creation is now being
done using `inkex.Effect.getDocumentHeight()` and
`inkex.Effect.getDocumentWidth()` methods which provide the necessary
fallback stuff if width/height or viewbox attributes are missing.
Wrapped methods into `TexText.get_document_height()' and
'TexText.get_document_width()` methods to provide compatibility with
Inkscape 0.48. Same for `uutounit` and `unittouu` to avoid repeated
try-except blocks in the processing code.
> Handle documents without width/height and/or viewbox specification

- textext.py
> fix flipping compensation for distorted nodes

- .travis.yml
- extension/textext/__init__.py
- extension/textext/asktext.py
- setup.py
> Revert "Improve error handling + setup.py update"

- .travis.yml
- extension/textext/__init__.py
- extension/textext/asktext.py
- setup.py
> Revert "Revert "Improve error handling + setup.py update""

- extension/textext/__init__.py
- extension/textext/asktext.py
- extension/textext/errors.py
- extension/textext/requirements_check.py
- extension/textext/utility.py
- pytests/test_compatibility.py
- setup.py
- test_installation_script.py
If this is OK for you @sizmailov I would like to merge this into the repo.
> Improved setup procedure/ Add lookup handles

- .travis.yml
- extension/textext/__init__.py
- extension/textext/requirements_check.py
- extension/textext/utility.py
- setup.py
- test_installation_script.py
Note: adjustments of .bat script are required if merged.
> Use current python for requirement checks

- extension/textext/requirements_check.py
Fix two serious errors. Both lead to false-positive requirements check.
> Fix requirements check

- extension/textext/requirements_check.py
@leberwurstsaft Can you confirm it works on you system?
Should be the final bit of #54
> add basic support for macos platform (untested)

- docs/source/install/linux.rst
> fix(doc): typo

- extension/textext/asktext.py
resolves #115 
New node can be initialized with 
- empty content (default)
- inline math template `$<cursor>$`
- display math template `$$<cursor>$$`
The choice is controlled by "New node content" GUI option, located at  "Settings" -> "New node content". 
Implemented in PyGTK only. Tk interface is not affected. 
> feat(ui): Add new node content UI option (PyGTK only)

- extension/textext/asktext.py
- extension/textext/requirements_check.py
Related issue(s): #122 #107 
Replace GTK2 with GTK3
> Migration to GTK3+

- extension/textext/requirements_check.py
Enables one to check for e.g. pstoedit versions < 3.74
Related issue: #126
> Possibility to check for gs/pstoedit versions by specifying an operator

- extension/textext.inx
- extension/textext/win_app_paths.py
@sizmailov Could you test this on your Linux installation with Inkscape 1.0alpha2, please?
> Remove of several unnecessary dependencies

- extension/textext/asktext.py
> Fixed: Shortcut CTRL+Q has no effect

- .travis.yml
- extension/textext/textext.inx
> Minor fixes

- textext/base.py
> More robust processing of log file parsing

- CHANGELOG.rst
- docs/source/usage/faq.rst
- docs/source/usage/gui.rst
Documentation update relating to #259 and release 1.2
Preview:
- https://jcwinkler.github.io/textext/usage/gui.html#invoking-textext-extension
- https://jcwinkler.github.io/textext/usage/faq.html#define-keyboard-shortcut
- https://jcwinkler.github.io/textext/changelog.html
> Documentation update for release 1.2

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.rst
- docs/source/usage/faq.rst
@sizmailov: Just some documentation updates for the next release.
> Documentation update for release 1.4.0

- .github/workflows/ci.yaml
@sizmailov I transitioned the tests to Github actions. 
Due to the request for signing the packages I will deploy packages from my local machine in the future. Doc build will be triggered by pushing a signed tag.
> Github actions: Setup of CI tests

- textext/base.py
> Fix a typo in the docstring

- AUTHORS.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/usage/command_line_usage.rst
- docs/source/usage/gui.rst
Useful for debugging and testing purposes.
@user202729 If you are interested, here is a preview: https://jcwinkler.github.io/textext/usage/command_line_usage.html (Side note: you have been referenced twice in AUTHORS.rst, hence I removed one item)
> Doc: Added command line usage section
