textext/textext

asktext.py
In Python 2.6 shipped with Inkscape 0.91 and prior the synatx
'Reset ({:.1f})'.format(reset_scale)
leads to a "Zero length field name in format" error.
=> Fixed "Zero length field name in format" error in Inkcape <= 0.91

textext.py
Fixes #10 "Error occurred while converting text from LaTeX to SVG"
Unfortunately when a node processed by TexText comes from an Inkscape
document that has never been saved before no version attribute is
provided by Inkscape. The corresponding call to the key fails. In these
cases no version attribute is stored in the TexText node. It is not
ideal but currently I do not see any other solution. Completely ommiting
this piece of information is not an option in my opinion. We should grab
what can be grabbed.
=> Fixed: Failure on missing inkscape version key

asktext.py, setup.py, textext.py
This patch fixes issues with position and scale of object that was scaled manually in inkscape and then re-edited with textext (see #11, #13). 
Now scaling of textext object in inkscape is coupled with "scale factor" in plugin window. This behavior match behavior of native text objects in inkscape, so this is definitely right way to handle it. 
Here are several cycles of `create -> edit in inkscape -> edit content in textext -> scale to 1.0 in textext` with different transformations in inkscape. 
Another improvement is addition of a control which allows to choose new positioning relative to old bounding box. This property is similar to "align" property of native text fields except it has two dimensions.
Here is an example of using this alignment property. The "original text" gets edited, …
=> Fix bad positioning

asktext.py, textext.py
This pull request offers an update of the Tk interface so it matches the functionality of the GTK interface. I know it is not a candidate for a design award. But it does what it is meant for.
Since combo boxes are not available in the Tk version shipped with Inkscape on Windows / Python 2.7 I used radio buttons.
Furthermore, I renamed the label of the `global` scale factor button to `From previous`according to the discussion in issue #16.
The scale buttons do show the full resolution of the factor now. (Do we really need 3 decimals?)
Open: Disable alignment controls when creating a new node (Tk and GTK).
=> Tk interface: Added TeX command selection and alignment control

default_packages.tex, textext.py
This pull request relates to issue #21.
If svg code coming from the converter contains non-black styles -> TeX colorization is kept
If everything is black coming from the converter -> Inkscape top level group color/ opacity is preserved
See commit messages for more details.
Note that pstoedit colorizes its items using "fill" etc. while pdf2svg uses css styles (as Inkscape). Neverthelss I check for both ways in both converters `is_colorized` methods. Maybe too paranoid?
Tested both converters in Inkscape 0.92.
=> Keep Inkscape / TeX colors

setup.py, test_installation_script.py
This PR is based on #53, so #53 should be merged first. 
This adds requirement checks to setup.py
Requirements are expressed in a form of expressions, so it's very easy to extend/modify without 
breaking the logic:
https://github.com/sizmailov/textext/blob/check_requirements_at_install/setup.py#L445-L481
Requirements has feature to extend printed messages depending on it's check result. It might be used to guide user through issues, provide links to docs, etc. 
The result of check is printed as a tree, so it's easy to tell what went wrong:
`test_installation_script.py` mocks required executables  to test `setup.py` in various situations.
For example this test case simulates version parse errors of ghostscript and pstoedit. Check is succeed because of available pdf2svg:
close #54
=> Check requirements at install

.travis.yml, extension/textext/__init__.py, extension/textext/asktext.py, setup.py
+ Added a logfile
+ Top-level error collection 
+ Exceptions are in hierarchy and more telling
+ Don't show same error twice (#17)
+ Suppress additional warning window in kde (missing theme)
+ Reduce `return None -> check for None -> raise` to simple `raise` at first place.
todo: if fatal error is unavoidable show it right away
+ each check marked with Succ/Fail/Ukwn (helpful if terminal does not support colors)
+ add option to suppress console colors
+ remove old installation (if any) by default
+ ask for preamble replacement confirmation iff old file exists and differs
=> Improve error handling + setup.py update

setup_win.bat
=> Call to setup.py reflects removed --python27-executable option

extension/textext/requirements_check.py
Reverts textext/textext#85
The modifications break the setup procedure, at least under Windows:
```
[TexText][INFO    ]: Using `inkscape-executable` = `C:\Program Files\Inkscape\\inkscape.exe`
Traceback (most recent call last):
File "C:/Users/winkler/Uni/Projekte/Allgemein/TexText/github/textext-jcwinkler/setup.py", line 333, in <module>
check_result = checker.check()
File "C:/Users/winkler/Uni/Projekte/Allgemein/TexText/github/textext-jcwinkler\extension\textext\requirements_check.py", line 735, in check
check_result = textext_requirements.check()
File "C:/Users/winkler/Uni/Projekte/Allgemein/TexText/github/textext-jcwinkler\extension\textext\requirements_check.py", line 407, in check
result = self.criteria()
File "C:/Users/winkler/Uni/Projekte/Allgemein/TexText/github/textext-jcwinkler\e …
```
=> Revert "Fix requirements check"

extension/textext/asktext.py
Preview image is limited in width, but not in height. Tall preview images inadequately shrink input text area and resize TexText window even beyond display size. 
This PR limits preview image height to 150 px.
=> fix(preview): limit height of preview image

extension/textext/__init__.py
pstoedit generates background rectangle in resulting svg, so exporting
with '--export-area-drawing' leads to whole page generation.
Fortunately pstoedit always(?) creates svg group with id="content"
and background goes to a separate rect instance with id="background"
Tested on windows and linux
=> fix(preview): trim pstoedit background

extension/textext/requirements_check.py
Nowadays UTF-8 is default encoding on most systems. But there plenty which use other encodings and it's leads to errors in `setup.py` when it interprets external programs output.
Due to lack of encoding detection in minimal distribution of python2.7 the patch simply ignores utf-8 decoding errors. It might lead to "Uknown" requirements check result, but it's better than crash. 
#101 
- [x ] Tested on Windows, Version: [10, 1803]
=> fix(requirements check): Ignore decoding errors of subprocess output

extension/textext/__init__.py
This should fix Issue #111, rebased to the `develop` branch. Please close one of the two PR's, leaving whichever branch you like better.
It just changes the location for the log file using the same methods already used for the settings file.
=> Fix Issue 111: Write log file to user-writable dir (Develop branch)

extension/textext/asktext.py
The
window.show()
self.normalize_ui_row_heights() # requires knowledge of rendered heights
window.hide()
window.show()
procedure leads to empty windows on some systems, see issue #114.
Hence, it has been removed here. The effect in layout is only marginal.
Resolves #114
=> Removed normalize_ui_row_heights in AskText ui setup

CHANGELOG.rst, docs/source/install/linux.rst, docs/source/usage/faq.rst
Add instructions to change default inkscape python interpreter
#129 
Short checklist: N/A: doc change only
=> Add instructions to change default inkscape python interpreter

extension/textext.inx
As It turns out, there was an undocumented option to hide "extension is working" window.
=> Remove `extension is working` window for inkscape<1.0

extension/textext/asktext.py
Relates to issue #127:
- Default close shortcut is ESC
- Confirmation for closing TT window when text has been changed
- Confirmation can be disabled
Remark: Maybe it would be "perfect" when also changes in scale factor etc. are detected. But due to lack of time I postpone this...
=> Window close confirmation (configurable)

.travis.yml, extension/textext/requirements_check.py, test_installation_script.py
This pull request is the first of two for re-enabling travis ci tests.
In this stage an app image of the alpha2 version of Inkscape is installed in the build machine and the installation procedure is tested. The next stage will re-enable the compatibility tests (or at least introduce a simple functional test).
Note: I wanted to have Inkscape 0.92.x and 1.0alpha2 in parallel on my test-machine. Hence I har-coded the alpha2 name and some places which is not very elegant but maybe OK for this test phase...
=> Feature/travis deploy for 1.0 (Stage 1 of 2)

extension/textext/__init__.py, extension/textext/requirements_check.py
A `print` statement, presumably used for debugging during development, found its way into the release. This results in the found version of Inkscape being the first bit of text sent back.
Inkscape may be able to handle this if valid content follows, but it upsets it if its the only thing returned (try just clicking cancel after opening the extension--you'll get an error).
This simply comments out that print statement, following the style in the rest of the file.
=> Remove a print statement from requirements_checker

extension/textext/__init__.py, extension/textext/asktext.py, extension/textext/errors.py, extension/textext/latexlogparser.py
This is one of the two patches in #146.
This patch handles unicode changes and changes to functionality in the `string` module. **These changes should be backwards compatible to (at least) python 2.7.12**.
=> Backwards compatible python 3 changes

docs/source/install/linux-beta.rst, docs/source/install/linux.rst, docs/source/install/windows-beta.rst, docs/source/install/windows.rst
I would like to provide instructions on how to test current development version of TexText with Inkscape 1.0 beta while Inkscape 0.94.x is also installed and on the system path.
This PR offers instructions for Linux, as I use it. You can see it here: 
https://jcwinkler.github.io/textext/install/linux-beta.html
Windows will follow.
If some more convenient ways are possible please let me know. Thanks!
=> Doc: Install instructions for Inkscape 1.0

setup.py, setup_win.bat
ghostscript, pstoedit, pdf2svg are not required anymore. Hence, the corresponding options have been removed from the setup scripts.
=> Removed deprecated setup options

extension/textext/win_app_paths.py, tests/win_app_paths/test_win_app_path.py
Windows only: We do only need to lookup the installation directory of Inkscape in the
Windows registry now. Hence, all the overhead needed to detect pstoedit,
ghostscript and pdf2svg is not required anymore.
not relevant: Tested on Linux, MacOS
=> Simplified win_app_paths.py

extension/textext/__init__.py, setup.py
#148 
- fix interactive install with python3
- embed `<defs>` tag in textext object
An alternative implementation with populating root `<defs>` would result to buggy copy to another document and potential pollution of root `<defs>`. 
Currently I'm not satisfied with id replacement performance. It takes 8 seconds on my machine on  first example from #148, therefore I mark the PR as a draft for now.
**Edit:** update tested inkscape version
=> Support `<defs>`

extension/textext/__init__.py
During debugging in PyCharm ``for k, v in locals().items():`` throws
the RuntimeError exception "Dictionary changed size during iteration".
I guess it is because locals() is modified by the IDE or something else.
With the provided fix the problem is solved.
=> Hotfix: "RuntimeError: dictionary changed size during iteration"

extension/textext/__init__.py
**Before:**
**After:**
In both cases scale factor 1.0 is used.
=> Hotfix: Scale factor is ignored in new nodes

extension/textext/__init__.py
Since exception thrown when acessing nonexising self.svg member
is silently ignored, the error did not show up during testing.
Furthermore the correct tag to query for is inkscape:version, not
version (have we been in the inkscape namespace by default in old
TexText verions?)
Finally set_meta is called instead of set so that namespace is correctly
set.
=> Fixed: Inkscape version never stored in TexText node

extension/textext/asktext.py
Preview was triggered by bare `P`, not `Ctrl+P`
=> Fix Ctrl+P shortcut

.travis.yml, extension/textext.inx
This PR adds .inx validation against `inkscape.extension.rng` from master branch of https://gitlab.com/inkscape/extensions
Changes:
`Tex Text` moved to `Text` sub menu 
=> Follow .inx schema

extension/textext/__init__.py
New nodes are not properly set in the center of the document.
**Situation before the fix**
**Situation after the fix**
Two reasons for this behavior:
https://github.com/textext/textext/blob/3f29077b6f440e2937de9c7e04505169e7b9102e/extension/textext/__init__.py#L426
In  fact ``tt_node.bounding_box()`` expands to ``x, w, y, h`` given in pt.
Furthermore
https://github.com/textext/textext/blob/3f29077b6f440e2937de9c7e04505169e7b9102e/extension/textext/__init__.py#L423-L424
returns units in mm (if user has mm for the document unit).
I use new method ``get_center_position()`` provided by Inkscape extension API now. Furthermore, I also removed the hand written ``get_document_width()`` methods (see commit message).
So, finally we now have: …
=> [WIP] Hotfix/wrong node placement

extension/textext/requirements_check.py
Fix path to user `extensions` directory 
Mac path is compatible with inkscape>=1.0beta2
Now paths are computed as follows:
```
Linux     ~/.config/inkscape/extensions
Windows   %APPDATA%\inkscape\extensions
MacOS     ~/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions
```
=> Fix macos extension dir path

extension/textext/asktext.py, extension/textext/requirements_check.py
Related issue(s): #173 
This PR re-enables TkInter support when the extension is run under Python 3. It is good to have this as backup since installation of gtk-bindings is still problematic (see e.g. discussion in #150)
=> Enabled TkInter under Python 3

docs/source/conf.py, docs/source/install/linux-beta.rst, docs/source/install/linux.rst, docs/source/install/windows-beta.rst, docs/source/install/windows.rst
Resolves issue #180
We need to provide both, download links as well as documentation to/ for  TexText 0.11 and TexText 1.0 in the future since it will take some time until Inkscape 1.0 will be the standard on all systems and for all users.
=> Doc: Fixed missing links to TexText 0.11 downloads

docs/source/install/linux-beta.rst, docs/source/install/windows-beta.rst
@sizmailov I just extended the installation instructions for TexText development versions by the GTK bindings. What do you think?
Please see https://jcwinkler.github.io/textext/install/linux-beta.html and https://jcwinkler.github.io/textext/install/windows-beta.html
Note that for the final release (i.e. without the AppImage) I provide a completely rewritten version of the help including new screenshots, troubleshooting section etc. I will inform you as soon as it is ready for review.
=> Added GUI binding installation instructions for beta releases

extension/textext/__init__.py
Thank you for your contribution to TexText. Please provide the following information before opening this pull request:
=> Fix dict_keys object is not subscriptable

extension/textext/__init__.py
Option is deprecated in most recent beta builds of Inkscape 1.0
Related issue(s): #188
=> Hotfix: Unknown option --without-gui

extension/textext/win_app_paths.py
If Inkscape is not found in the defauilt location on Windows
an empty list needs to be returned in order to build a
correct tweaked system path later.
See issue #186
=> Hotfix: Illegal return of None object instead if empty list

extension/textext/__init__.py
Inkscape command line option --export-filename has been changed to --export-filename in Inkscape.
Related issue(s): #188
This change is currently not available in Linux beta builds, only on Windows. Hence, I will keep this PR open until the option is available there.
=> Fixed: Unknown option --export-file

extension/textext/__init__.py
Shortens import statements according to latest inkscape extensions guidelines.  
Note: latest extensions are not included (yet) in inkscape repo nor in bundle in CI. 
Fixes #194 
=> Shorten import statements

textext/base.py
Fixes illegal vertical flipping of re-compiled old TexText nodes
Related issue: #205
=> Hotfix: Recompiled TexText <= 0.11.x nodes flip vertically

textext/base.py
#206
- Fixes coloring bug
- Open hash in binary mode to avoid possible unicode errors
=> Fixes 2020 04 15

setup.py, textext/utility.py
Respect user-provided ext directory path in setup.py
Fixes #211
=> Fix: use inkscape_extensions_path in setup.py

setup.py, setup_win.bat, tests/win_app_paths/test_win_app_path.py, textext/win_app_paths.py
As it turned out Inkscape windows registry keys have been changed in the new 1.0 inkscape installers. Additionally, the registry keys are written into the wrong registry mapping, i.e. Inkscape 64bit is registered as 32bit application on 64bit Windows (I am in contact with Patrick w.r.t this but I am not sure that this will be fixed until Monday). This requires additional search options.
The PR reflects these facts:
- in `setup_win.bat` so the script is able to find the Python interpreter
- in `win_app_paths.py` so we can correctly tweak the path in TexText
Furthermore, it turned out that the way `setup_win.bat` has to invoke `setup.py` via Inkscape's Python interpreter leads to the problem, that the setup log is written into the directory in which python.exe resides. This is read-only for …
=> Account for changed registry keys

textext/base.py
Parsing lualatex produced error log fails with the error message
```
'charmap' codec can't decode byte 0x9d in position 1003: character maps to <undefined>
```
This PR fixes the problem on Python2 and Python3
=> Fixed: LuaLaTeX log not correctly parsed

textext/base.py
Fixes: Nodes created with TexText <= 0.6 cannot be re-compiled.
TexText up to version 0.6 did only offer pstoedit converter backend.
Hence, the corresponding pdfconverter flag is missing in such nodes 
and integration of the compiled svg snippet fails when current TexText 
tries to access this flag. Now it uses pstoedit as default converter if it 
does not find a pdfconverter flag.
=> Fixed: TexText 0.6 nodes cannot be re-compiled

textext/asktext.py, textext/base.py
=> Add extra UI option to set preview bg to white

docs/source/install/linux.rst
Related issue(s): 
None
Fix a typo in the documentation page for installation in linux
=> Fix typo in linux installation docs

setup_win.bat
Resolves #232
@cedricesc could you check it in your configuration with spaces in path using the attached file? Thanks!
[TexText-Windows-1.1.0.zip](https://github.com/textext/textext/files/4937666/TexText-Windows-1.1.0.zip)
=> Fixed: setup_win.bat fails if spaces are in path

textext/base.py
=> Hotfix: Stroke color of inkscape colored nodes not kept

textext/base.py
For each element which has the style attribute "stroke"
set to "none" a style attribute "stroke-width" with
value "0" is added. This ensures that when colorizing
the node later in inkscape by setting the node and
stroke colors letters do not become bold (letters have
"stroke" set to "none" but e.g. horizontal lines in
fraction bars and square roots are only affected by
stroke colors so for full colorization of a node you
need to set the fill as well as the stroke color!).
**Colorized node (fill + stroke color) before this commit:**
**Colorized node (fill + stroke color) after this commit:**
What do you think @sizmailov?
=> Add "stroke-width=0pt" to SVG elements with "stroke=none"

textext/utility.py
**Before fix:**
```bash
[2020-08-24 00:28:10,253][DEBUG   ]: TexText version = '1.1.0' (md5sum = b8e2f0897e7bf7607690ffcf8c569772)          //  (unknown file):0    
[2020-08-24 00:28:10,253][DEBUG   ]: platform.system() = 'Windows'          //  (unknown file):0    
[2020-08-24 00:28:10,253][DEBUG   ]: platform.release() = '10'          //  (unknown file):0    
[2020-08-24 00:28:10,253][DEBUG   ]: platform.version() = '10.0.18362'          //  (unknown file):0    
[2020-08-24 00:28:10,253][DEBUG   ]: platform.machine() = 'AMD64'          //  (unknown file):0  
```
**After fix:**
``` bash
[2020-08-24 00:05:47,744][DEBUG   ]: TexText version = '1.1.0' (md5sum = b8e2f0897e7bf7607690ffcf8c569772)          //  base.py:145  
[2020-08-24 00:05:47,744][DEBUG   ]: platform.system() = 'Windows' …
```
=> Fixed: Fileinfo not shown in log file

textext/asktext.py
Relates to #253
Inkscape 1.0.1 on Windows is shipped with a Python subsystem which differs from the one shipped with Inkscape 1.0.0. As a consequence, due to changes in the gobject introspection system, the harfbuzz.typelib is not packaged in Inkscape 1.0.1 on Windows. This workaround adds the texttext extension directory to the the search path for the typelibs. Windows packages of TexText are now manually equipped by me with the missing harfbuzz typelib.
I know that we do again "fixing" errors which are in fact Inkscape errors. But I do not want to wait months until an Inkscape fix is released and TexText users are forced to use the antique TK interface.
I will remove this fix when a fixed Inkscape version is released (most probably 1.0.2). See also the correpsonding merge request in …
=> Workaround: Missing harfbuzz typelib in Inkscape 1.0.1

setup.py
Relates to #255 and fixes #262
In `setup.py` the harfbuzz.typelib missing in Inkscape but shipped as a workaround in TexText 1.2 is not seen. Hence, the setup complains about missing gtk bindings. 
The PR fixes this issue. (Harfbuzz.typelib is packed manually by me into the Windows packages)
=> Hotfix (Windows): GTK3 not detected during installation

setup.py
Python creates a bunch of temporary files which are copied on installation. Might be useful for devs only.
=> Don't copy temporary files on install

textext/base.py
Use `unicode_escape` for `text`. 
Don't apply encoding when reading nodes created with TexText==1.2.0
Note: to test the patch VERSION needs to be changed :warning: 
Closes #265 
=> Use `unicode_escape` for all new nodes

setup_win.bat
When Inkscape is installed on Windows using the MSI installer the
registry keys are not set as it is done when using the NSIS installer.
In fact, no valid registry keys are set from which anything about the
install location can be concluded. Hence a simple trial and error method
has been added to the batch file script to resolve this in the most
likely cases.
The problem also occured as a side effect in #280 
=> Windows installer: Better handling of MSI Inkscape installations

README.rst, docs/source/install/linux.rst
Skipping the checklist, since it isn't really relevant.  This merge simply updates the documentation reflecting the presence of the inkscape-textext package in both [Debian](https://packages.debian.org/source/testing/inkscape-textext) and [Ubuntu](https://launchpad.net/ubuntu/+source/inkscape-textext).
This doesn't update the readme, maybe that should be updated as well?
=> Update documentation reflecting Debian packaging

docs/source/conf.py, docs/source/install/linux.rst, docs/source/install/macos.rst, docs/source/install/windows.rst, docs/source/usage/troubleshooting.rst, setup_win.bat
This PR addresses three improvements in the documentation:
- The messages of the Windows setup script `setup_win.bat` are more precise now and do clearly state and illustrate what is meant. This addresses issue #280
- The command line options of the setup script are explained in detail and are associated with the corresponding setup scenarios/ problems. This addresses issue #276 (see https://github.com/textext/textext/issues/276#issuecomment-761868727). 
Here is a rendered version: [Setup-Script options](https://jcwinkler.github.io/textext/usage/troubleshooting.html) referenced in [Linux](https://jcwinkler.github.io/textext/install/linux.html#linux-install-textext), [Windows](https://jcwinkler.github.io/textext/install/windows.html#windows-install-textext), and …
=> Improvement of documentation (setup script, Debian packages)

setup_win.bat, textext/win_app_paths.py
Inkscape MSI installer uses different registry keys compared to NSIS installer. Hence, if Inkscape has been installed in a non-standard directory on Windows, setup fails. This is fixed now.
See Inkscape [commit](https://gitlab.com/jcwinkler/inkscape/-/commit/33de3f795262a7460684e4079ee25b2f34dabb18) and [merge](https://gitlab.com/inkscape/inkscape/-/merge_requests/2863) and [discussion](https://gitlab.com/inkscape/inkscape/-/issues/2255).
=> Windows: Detect path to Inkscape when Inkscape has been installed via MSI installer

snippets/transformed-layers.svg, textext/base.py
When layers have a transform attribute new LaTeX snippets were not placed in the center of the view but somewhere else in the document. They also appeared vertically flipped or rotated sometimes. This is fixed by this pull-request. We iterate over the current layer and all of its parents to get the overall re-transformation for correct placement of the node
Related issues: #313, #283
=> Account for layer transforms during node placement

textext/base.py
So the order is script location, inkscape_extensions_path, cwd
Fixes issues with non-writable log location
Related issue(s): #314
Tries to write first into script locatin, then inkscape_extensions_path, then the current working directory.
It sets up the user channel first so in any case the logs are accessible if you decide to later show the logs if
using/setting up the file logger fails
Not tested yet, should work fine though.
=> base: Rework logging location

setup.py, textext/base.py, textext/requirements_check.py, textext/utility.py
This pull request addresses two subjects:
- when TexText is installed system wide it is ensured that no files are written into the install location (which usually is read only for the user)
- the setup script offers an option `--all-users` which will install TexText into the system extension dir of Inkscape
In order to make this work it must be ensured that `textext.log` and `config.json` go into a directory which has write acces for the user. I decided to put these files into the following directories:
~- Linux: `~/.config/textext`~
~- Windows: `C:\Users\Username\AppData\Roaming\textext`~
~- Mac: `~/Library/Application Support/org.inkscape.Inkscape/config/textext`~
**Linux:**
- Settings: `~/.config/textext/config.json`
- Logs: `~/.cache/textext/textext.log`
**Windows:** (%APPDATA% = …
=> Enable/ fully support system wide installation

textext/asktext.py
When reading TeX code from a file (File - Open menu in TexText dialog) the following error is shown in TexText 1.6.0:
`ResourceWarning: unclosed file <_io.TextIOWrapper name'...'`
This patch fixes this error.
Closes #322
=> Fixed: ResourceWarning error when reading TeX-code from file

textext/requirements_check.py
The python standard module `distutils` is deprecated as of Python 3.10 and scheduled for removal.  textext depends on distutils for parsing the version of the inkscape binary, which results in an ugly warning in inkscape.
We replace the version parsing with a simple regex.
=> Replace dependency on distutils with manual version parsing.

snippets/empty_i1_1_0.svg, snippets/empty_i1_1_0_in.svg, snippets/empty_i1_1_0_px.svg, snippets/empty_i1_2_0.svg, snippets/empty_i1_2_0_in.svg, snippets/empty_i1_2_0_px.svg, textext/base.py, textext/utility.py
Related issue(s): Resolves #338 
Pull request addresses the fact that in Inkscape 1.2. the extension API method [`unittouu`](https://inkscape.gitlab.io/extensions/documentation/source/inkex.elements._base.html#inkex.elements._base.BaseElement.unittouu) always converts a value into px and not into the units specified by the user. Hence, the view_center is always returned in px now and not in the units selected by the user in its document. Depending on the API version the view_center coordinates are converted into the correct unit now.
```python
if hasattr(inkex, "__version__"):
if check_minimal_required_version(inkex.__version__, "1.2.0"):
view_center.x = self.svg.uutounit(view_center.x, self.svg.unit)
view_center.y = self.svg.uutounit(view_center.y, self.svg.unit)
```
([Code …
=> Feature/user units inkscape 1.2

docs/source/usage/faq.rst, docs/source/usage/gui.rst, textext/base.py, textext/default_packages.tex
Related issue(s): none
**Reasoning**: My reason for this PR is that I want to create figures for a document where the normal font size is set to 11pt (instead of the default 10pt) and I do not want to manually specify that font size in every textext cell. The proposed change allows to have a `documentclass`-like command in the preamble which makes it easy to "globally" specify things like the normal font size. The change does not alter the behavior for preambles without such a command. It is fully backwards compatible.
**Implementation**: I moved `\documentclass{article}` from the `DOCUMENT_TEMPLATE` into its own constant called `DEFAULT_DOCUMENT_CLASS`. This constant is only prepended to `preamble` if it does not contain a …
=> Allow optional \documentclass or \documentstyle in preamble

.github/workflows/ci.yaml, textext/asktext.py
Each time any Inkscape extension with a custom GUI is executed under Python 3.10 the warning
```
<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
```
is shown. This is pretty annoying. This is a weird workaround to suppress this warning.
Resolves #350
Related to #361, #362
(cherry picked from commit 52d4c03076c3c66a1af081c3b3c8cf3494902064)
=> Suppress ImportWarning

.github/workflows/ci.yaml, .pylintrc
Closes #377 
Implements linting with pylint in Github Actions and adds a template `.pylintrc`.
=> Add linting in CI

textext/requirements_check.py
Related issue(s): https://github.com/textext/textext/issues/403#issuecomment-1817494909
On Windows, executables end with `.exe`. The setup script thought `typst is NOT found in PATH` by default, because it does not know `typst.exe`. This PR tells it to check `typst.exe`.
(Sorry this is a trivial PR so I didn't test rigorously)
=> Fix `typst.exe` ignored on Windows 

.gitignore, textext/asktext.py
Related issue(s):https://github.com/textext/textext/issues/417
In typst, the display math is marked as `$ Formula $`.
This pull changes the build-in text if user is using Typst.
=> custumize typst displayMath

textext/base.py
Reason is an additional path attribute in the genreated SVG since typst 0.12. 
By setting the page background to none this is avoided.
Resolves  #438
=> Fix: Typst nodes fill complete page

textext/LATEX_OPTIONS, textext/base.py
**Background.** I have been trying to use the latex [minted](https://ctan.org/pkg/minted?lang=en) package for syntax highlighting together with the ``textext`` plugin. The package works, but requires the ``-escape-shell`` option to be set for the latex executable.
**Changes.** Since the ``-escape-shell`` option probably does not make sense as a default and others might want to customize the latex options differently in the future, I added a way to customize the options without modifying the code.
I added a file ``LATEX_OPTIONS`` to the ``textext`` plugin folder. Each line in this file represents one option given to the latex executable. This options file is loaded in the constructor of the ``TexToPdfConverter`` class to overwrite the default values in the …
=> Added Option to customize Latex Command Line Options

setup.py
There are two cases where `python setup.py` would previously cause trouble:
1. when the user `git clone` into `~/.config/inkscape/extensions/textext` itself. Then `python setup.py` would wipe the git repository.
2. when `~/.config/inkscape/extensions/textext` is a symbolic link. Then `shutil.rmtree` would raise
```
Traceback (most recent call last):
File ".../textext/setup.py", line 488, in <module>
remove_previous_installation(args.inkscape_extensions_path)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".../textext/setup.py", line 218, in remove_previous_installation
shutil.rmtree(file_or_dir)
~~~~~~~~~~~~~^^^^^^^^^^^^^
File "/usr/lib/python3.13/shutil.py", line 763, in rmtree
_rmtree_safe_fd(stack, onexc)
~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
File …
```
=> Avoid trouble in paradoxical configurations

textext/base.py
Using inkex API to set unique IDs for the node and also its children. Ensures that
the old node is still selected completely after TexText closes, see #460.
Resolves #460
@user202729 I think this fixes the problem. If you have the time, you may test it.
=> Unique IDs also in children

textext/asktext.py, textext/base.py
Allow the user to configure the GUI toolkit being used, either GTK or TK.
The motivation is to make testing (whether some change works in both TK and GTK) in development easier. Previously I think in order to test TK you need to uninstall GTK.
Currently there's no GUI to configure it yet (since there are only two I'm thinking making just a single button "switch to GTK GUI" / "switch to TK GUI"). I manually edit `config.json` in `~/.config/textext/` (on Linux) and add e.g.
```
{
"preamble": ...
"scale": 1.0,
"previous_tex_command": "pdflatex",
"gui": {
"toolkit": "tk",  // << add this
"confirm_close": true
}
}
```
Because currently there's no GUI, I think raising hard error (instead of handle it gracefully) is acceptable. Feature to e.g. automatically fallback to the other GUI and warn the …
=> Allow the user to select GUI toolkit

textext/asktext.py
Fixes https://github.com/textext/textext/issues/473
=> Fix Gtk warning
